Revert "hwloc: upgrade 2.12.2 -> 2.14.0"
ERROR: hwloc-2.14.0-r0 do_populate_lic: QA Issue: hwloc: The LIC_FILES_CHKSUM does not match for file://COPYING;md5=79179bb373cd55cbd834463a514fb714
hwloc: The new md5 checksum is 883e49a2e0f7142a345f9b0c01a380e7

This reverts commit 1e04c7da0d7088ea21733608dddd7d2b58349ad1.